trigger:
  - main

pool:
  name: 'Default'

variables:
  - group: docker-creds
  - group: image-cred
  - group: github
  - name: IMAGE_TAG
    value: $(Build.BuildId)

stages:




  - stage: TerraformDeploy
    displayName: 'Terraform'
    dependsOn: BuildPush
    jobs:
      - job: Terraform
        steps: 
          - task: TerraformCLI@2
            inputs:
              command: 'init'
              backendType: 'aws'
              allowTelemetryCollection: true
              backendServiceAws: 'aws-modern-connection'
              backendAwsRegion: 'ap-south-1'

          - task: TerraformCLI@2
            inputs:
              command: 'plan'
              allowTelemetryCollection: true
              providerServiceAws: 'aws-modern-connection'
              providerAwsRegion: 'ap-south-1'
             

          - task: TerraformCLI@2
            inputs:
              command: 'apply'
              allowTelemetryCollection: true
              providerServiceAws: 'aws-modern-connection'
              providerAwsRegion: 'ap-south-1'
               
          - task: TerraformCLI@2
            inputs:
              command: 'destroy'
              allowTelemetryCollection: true
              providerServiceAws: 'aws-modern-connection'
              providerAwsRegion: 'ap-south-1'
