trigger:
  - main

pool:
  name: 'Default'

variables:
  - group: docker-creds
  - group: image-cred
  - group: github
  - name: IMAGE_TAG
    value: $(Build.BuildId)

stages:
  - stage: DockerLogin
    displayName: Docker Login
    jobs:
      - job: DockerLogin
        steps: 
          - script: |
              echo "$(DOCKER_PASSWORD)" | docker login -u "$(DOCKER_USERNAME)" --password-stdin
            displayName: 'Docker Login'

  - stage: BuildPush
    displayName: Build, Push and Update main.tf
    dependsOn: DockerLogin
    jobs:
      - job: DockerBuildPush
        steps:
          - script: |
              set -e
              echo "Building Docker image: $(IMAGE_NAME):$(IMAGE_TAG)"
              docker build -t $(IMAGE_NAME):$(IMAGE_TAG) .

              echo "Pushing image..."
              docker push $(IMAGE_NAME):$(IMAGE_TAG)

              echo "Updating main.tf..."
              sed -i "s|REPLACE_ME_IMAGE|$(IMAGE_NAME):$(IMAGE_TAG)|" main.tf
              echo "main.tf after update:"
              cat main.tf
            displayName: 'Build, Push and Update main.tf'
          - script: |
              git fetch origin
              git checkout -B $(Build.SourceBranchName) origin/$(Build.SourceBranchName)
              git config user.email "amuthakrishna1988@gmail.com"
              git config user.name "amuthakrishna"
              git add main.tf
              git diff --cached --quiet && echo "No changes to commit" && exit 0
              git commit -m "Update container_image to $(IMAGE_NAME):$(IMAGE_TAG)"
              git remote set-url origin https://"$(gituser)":"$(gitpassword)"@github.com/amuthakrishna/laravel-simple-blog.git
              git push origin $(Build.SourceBranchName)
            displayName: 'Commit updated main.tf'



  - stage: TerraformDeploy
    displayName: 'Terraform'
    dependsOn: BuildPush
    jobs:
      - job: Terraform
        steps: 
          - task: TerraformCLI@2
            inputs:
              command: 'init'
              backendType: 'aws'
              allowTelemetryCollection: true
              backendServiceAws: 'aws-modern-connection'
              backendAwsRegion: 'ap-south-1'

          - task: TerraformCLI@2
            inputs:
              command: 'plan'
              allowTelemetryCollection: true
              providerServiceAws: 'aws-modern-connection'
              providerAwsRegion: 'ap-south-1'
              commandOptions: '-var="container_image=$(IMAGE_NAME):$(IMAGE_TAG)"'

          - task: TerraformCLI@2
            inputs:
              command: 'apply'
              allowTelemetryCollection: true
              providerServiceAws: 'aws-modern-connection'
              providerAwsRegion: 'ap-south-1'
              commandOptions: '-auto-approve -var="container_image=$(IMAGE_NAME):$(IMAGE_TAG)"'
              
